import React from 'react';
import './App.css';

// Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
import {Amplify} from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';

// Imports the Quiz component from Quiz.js for use in this file.
//import Quiz from './Quiz';

import { Auth } from 'aws-amplify';

// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
Amplify.configure(awsExports);


function App() {

  const checkUserRole = async () => {
    const user = await Auth.currentAuthenticatedUser();
    const groups = user.signInUserSession.accessToken.payload["cognito:groups"];
    if (groups) {
      if (groups.includes('Admin')) {
        return 'Admin';
      } else if (groups.includes('Sponsor')) {
        return 'Sponsor';
      } else if (groups.includes('Driver')) {
        return 'Driver';
      }
    }
    return 'User'; // Default role if no group found
  };

  return (
    <div className="App">
      <Authenticator>
        {({ signOut, user }) => {
          const role = checkUserRole();
          return (
            <main>
              <header className='App-header'>
                {/* Display content based on user role */}
                {role === 'Admin' && <h2>Welcome Admin!</h2>}
                {role === 'Sponsor' && <h2>Welcome Sponsor!</h2>}
                {role === 'Driver' && <h2>Welcome Driver!</h2>}
                
                {/* Sign Out Button */}
                <button 
                  onClick={signOut} 
                  style={{ 
                    margin: '20px', 
                    fontSize: '0.8rem', 
                    padding: '5px 10px', 
                    marginTop: '20px'
                  }}
                >
                  Sign Out
                </button>
              </header>
            </main>
          );
        }}
      </Authenticator>
    </div>
  );
}

export default withAuthenticator(App);